"""episodic events table

Revision ID: adac8c5072b0
Revises: e58288f41ec2
Create Date: 2026-07-09 08:19:41.775903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'adac8c5072b0'
down_revision: Union[str, Sequence[str], None] = 'e58288f41ec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episodic_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_episodic_events'))
    )
    op.create_index(op.f('ix_episodic_events_created_at'), 'episodic_events', ['created_at'], unique=False)
    op.create_index('ix_episodic_events_session_created', 'episodic_events', ['session_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_episodic_events_session_id'), 'episodic_events', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_episodic_events_session_id'), table_name='episodic_events')
    op.drop_index('ix_episodic_events_session_created', table_name='episodic_events')
    op.drop_index(op.f('ix_episodic_events_created_at'), table_name='episodic_events')
    op.drop_table('episodic_events')
    # ### end Alembic commands ###
